baseURL = "https://phtc.ctl.columbia.edu/"
metaDataFormat = "yaml"
languageCode = "en-us"
title = "Region 2 Public Health Training Center"
googleAnalytics = "UA-311226-27"
copyright = "Copyright (c) 2018 Center for Teaching and Learning at Columbia University - Code licensed GNU GPLv3, content CC BY-NC-SA 4.0"

[params]
    description = "A collection of competency-based public health and subject-related online trainings by the Region 2 Public Health Training Center."
    keywords = "public health training, public health"
    author = "Region 2 Public Health Training Center"
    shortTitle = "PHTC"
