baseURL = "https://phtc.ctl.columbia.edu/"
metaDataFormat = "yaml"
languageCode = "en-us"
title = "New York City—Long Island—Lower Tri-County Public Health Training Center"

[params]
    description = "A collection of competency-based public health and subject-related online trainings by the New York City—Long Island—Lower Tri-County Public Health Training Center."
    keywords = "public health training, public health"
    author = "New York City—Long Island—Lower Tri-County Public Health Training Center"
    shortTitle = "PHTC"
